# Site settings
title: Gautam Malhotra
description: GM-oriented product leader scaling global SMB and Enterprise SaaS
email: gmalhotra86@gmail.com
url: "https://gautamm.com"
linkedin_username: gautam-malhotra

# Build settings
plugins:
  - jekyll-seo-tag

# Google Analytics
google_analytics: # Add your GA4 measurement ID here after setup

# Exclude files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
